social:
  instagram: "https://instagram.com/ebiyasg"
  contact: "/contact/"
  email: "mailto:bennyyuen@consultant.com"
  map: "https://www.google.com/search?sca_esv=64ac0ab895c5266b&rlz=1CDGOYI_enSG1089SG1090&hl=en-GB&sxsrf=ANbL-n42cWd0W-PF_g4aC4ESjU_6QmgK_w:1769312886159&kgmid=/g/11p654bwpf&q=Millage&shem=bdslc,ptotple,shrtsdl&shndl=30&source=sh/x/loc/act/m1/3&kgs=2aeb6603ed0d6828&utm_source=bdslc,ptotple,shrtsdl,sh/x/loc/act/m1/3"

nav_items:
  - title: Services
    url: /about
  - title: Contact Us
    url: /contact
